### ISSUE TITLE
"Unable to import module 'lambda_function': cannot import name 'exceptions' from 'cryptography.hazmat.bindings._rust' (unknown location)

### ISSUE THREAD

**Issue by RanjitRamakrishnan** [pyca/cryptography#10361]
If you're filing a bug (as opposed to a feature request), please try the
following things:

* Check the FAQ to see if your issue is covered there:
  https://cryptography.io/en/latest/faq.html
* Upgrade to the latest version of ``setuptools`` and ``pip``
* Make sure you're on a supported version of OpenSSL
* Try with the latest version of ``cryptography``
* Be sure you have the required compilers (both a C compiler and Rust)
  installed if you aren't using the binary wheels.

If none of that works, please make sure to include the following information in
your bug report:

* Versions of Python, ``cryptography``, ``cffi``, ``pip``, and ``setuptools``
  you're using
* How you installed ``cryptography``
* Clear steps for reproducing your bug

Please do not report security issues on Github! Follow the instructions in our
documentation for reporting security issues:
https://cryptography.io/en/latest/security.html

**Comment by alex** [comment]
Your issue contains no details. If you'd like help debugging this, you need to provide information on how to reproduce this.

**Comment by RanjitRamakrishnan** [comment]
I am trying to encrypt data and load into a file. I use random encryption key for encrypt and encrypt the same with KMS key in lambda function

**Comment by alex** [comment]
How are you building your lambda?

**Comment by RanjitRamakrishnan** [comment]
It simple lambda code for encryption of files. I have added cryptography package as lambda layer.

**Comment by RanjitRamakrishnan** [comment]
I am trying to encrypt the content 

                kms_client = boto3.client('kms')
                data_key_response = kms_client.generate_data_key(
                    KeyId=kms_key_id,
                    KeySpec='AES_256'
                )
                plaintext_key = data_key_response['Plaintext']
                encrypted_key = data_key_response['CiphertextBlob']

                # Encrypt the file content with AES
                backend = default_backend()
                cipher = Cipher(algorithms.AES(plaintext_key), modes.CTR(os.urandom(16)), backend=backend)
                encryptor = cipher.encryptor()
                encrypted_content = encryptor.update(response.content) + encryptor.finalize()

                # Get the current date and time in YYYYMMDD_HHMISS format
                timestamp = time.strftime('%Y%m%d_%H%M%S')

                # Upload the encrypted file and encrypted data key to S3 with timestamp in the filename
                s3 = boto3.client("s3")
                s3_key = f"{s3_key_prefix}{export_name}_{timestamp}.csv"  # Adjusted the key to include export name and timestamp

                s3.put_object(Body=encrypted_content, Bucket=s3_bucket_name, Key=s3_key)
                s3.put_object(Body=encrypted_key, Bucket=s3_bucket_name, Key=f"{s3_key_prefix}{export_name}_key")

**Comment by RanjitRamakrishnan** [comment]
I have updated the code here. Please check

**Comment by alex** [comment]
You have still not provided any information on how you are building your lambda (i.e., how you are installing cryptography).

**Comment by RanjitRamakrishnan** [comment]
Cryptography packages is deployed as lambda layer and lambda code is build using cloud formation stack in service catalog.

It is basic lambda code for encrypt the content in the variable and put it in the S3 bucket.

**Comment by alex** [comment]
You are not providing _nearly_ enough detail.

Please understand: this package is installed, successfully, millions of times per day. Whatever is not working here is specific to _your_ environment. We cannot help if you do not provide specific details about how you are installing.
