### ISSUE TITLE
Segfault from hazmat/backends/openssl/ciphers.py

### ISSUE THREAD

**Issue by nchammas** [pyca/cryptography#2749]
Continuing the discussion from [here](http://bugs.python.org/issue26463).

Running Python 3.5.1 and Cryptography 1.2.2 (via AsyncSSH) on OS X 10.11.3.

I've attached the stacktrace generated when I enable Python's [`faulthandler`](https://docs.python.org/dev/library/faulthandler.html).

[`stacktrace.txt`](https://github.com/pyca/cryptography/files/152840/faulthandler-stacktrace.txt) / [`segfault.txt`](https://github.com/pyca/cryptography/files/152852/segfault.txt)

I don't have a minimal repro, unfortunately, but this happens consistently for me so I should be able to add more helpful information if you point me in the right direction.

**Comment by reaperhulk** [comment]
Does this bug occur if you install cryptography 1.1.2?

**Comment by nchammas** [comment]
Nope, I get a different stack trace (probably just from my app) and no segfault: [`cryptography-1.1.2-stacktrace.txt`](https://github.com/pyca/cryptography/files/153713/cryptography-1.1.2-stacktrace.txt)

**Comment by nchammas** [comment]
Does this mean this is a known issue?

**Comment by reaperhulk** [comment]
It means it's directly related to the static callbacks (a feature of cffi that was added for cryptography). Unfortunately it appears there are still issues with them in a variety of contexts... @alex I'm starting to wonder if we should revert static callbacks for now, although I'm not sure how we can get the bugs fixed without having people experiencing the problem giving us reproducers.

@nchammas can you supply a reproducer that doesn't contain any proprietary app code so that we can report it upstream to cffi?

**Comment by nchammas** [comment]
Hmm, I'm having trouble reproducing this just by connecting to localhost with AsyncSSH.

My current repro of the issue requires installing [Flintrock](https://github.com/nchammas/flintrock) from GitHub at [this branch](https://github.com/nchammas/flintrock/pull/77) and also requires an AWS account to launch instances on EC2. That's a bit much for a reproduction.

Are there any clues I can look into to help me boil this down to a more minimal repro?

The basic structure of the problem is this:
* I have several coroutines running commands against remote hosts via AsyncSSH, which uses Cryptography.
* In the middle of a command execution -- say I run `sleep 10` against a remote instance and am waiting for that to finish -- I hit `Control + C` to interrupt my program.

This triggers the segmentation fault.

**Comment by reaperhulk** [comment]
This is related to the way Python shuts down. As it calls `Py_Finalize` it will start deallocating various things. Unfortunately it appears it's deallocating in an inappropriate order that's causing a crash for you. cffi attempted to handle this in the 1.5.1/1.5.2 release but we've had various reports that it's still not quite working properly. Just to confirm: are you up-to-date with cffi?

**Comment by nchammas** [comment]
```
$ pip freeze | grep cffi
cffi==1.5.2
```

**Comment by reaperhulk** [comment]
Okay, so definitely a problem with the latest cffi still. Hopefully you can come up with a more minimal reproducer. cc @arigo in case he has ideas on how to make this easier to reproduce/fix.

**Comment by nchammas** [comment]
I'm also open to tips on how to debug this a bit myself so I can point y'all to something more specific. I'm gonna try fooling around with [`pudb`](https://pypi.python.org/pypi/pudb/) this week to see if I can give myself some more specific clues on what's going wrong.

**Comment by arigo** [comment]
I had "fun" doing the embedding support on CPython, which is its own mess, but I didn't expect shutdown in regular cases to also be such a mess...  I can only guess that calling a Python function when the interpreter is in the middle of Py_Finalize() is a Very Bad Idea.

**Comment by reaperhulk** [comment]
@arigo we appear to only be seeing this on Python 3.5. Would it be worth reporting it to CPython since apparently `Py_Finalize` behaves significantly differently there than in previous CPython releases? Maybe they can "fix" the behavior for 3.5.2?

**Comment by arigo** [comment]
Uh.  I guess we need to figure out what changed then...

**Comment by arigo** [comment]
Py_Finalize() itself didn't change between 3.4 and 3.5, but some other function called by it may have.  I can't debug this without having an example, though.  For now, I rewrote the way cffi stores ``@def_extern`` in ab9941c073b3 in a way that should fix another issue, and also in a way that I guess might maybe help here.  If you can get some of these users to try out this new version (not released yet), it would be cool!

**Comment by reaperhulk** [comment]
Thanks @arigo! @nchammas would you be able to try out that cffi patch (you can grab the master branch from https://bitbucket.org/cffi/cffi and it will contain the commit Armin mentioned) and see if it resolves your problem?

**Comment by nchammas** [comment]
@arigo - Would this be the best way to install the latest cffi from Hg?

```
pip install -U hg+https://bitbucket.org/cffi/cffi@default
```

**Comment by arigo** [comment]
Yes, that command works (just tried it myself to be sure).

**Comment by nchammas** [comment]
OK. I got thrown off at first since the version in Hg is still 1.5.2. (I was expecting something like 1.5.3.dev0.)

Anyway, installing cffi from hg and retrying my original operation yields this failure:

```
$ flintrock launch nick
Traceback (most recent call last):
  File ".../venv/bin/flintrock", line 9, in <module>
    load_entry_point('Flintrock', 'console_scripts', 'flintrock')()
  File ".../venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 549, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File ".../venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2542, in load_entry_point
    return ep.load()
  File ".../venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2202, in load
    return self.resolve()
  File ".../venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2208, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File ".../flintrock/__main__.py", line 5, in <module>
    from .flintrock import main
  File ".../flintrock/flintrock.py", line 15, in <module>
    from . import ec2
  File ".../flintrock/ec2.py", line 15, in <module>
    from .core import FlintrockCluster
  File ".../flintrock/core.py", line 10, in <module>
    from .ssh import (
  File ".../flintrock/ssh.py", line 11, in <module>
    import asyncssh
  File ".../venv/lib/python3.5/site-packages/asyncssh/__init__.py", line 23, in <module>
    from .agent import SSHAgentClient, connect_agent
  File ".../venv/lib/python3.5/site-packages/asyncssh/agent.py", line 20, in <module>
    from .public_key import SSHKeyPair
  File ".../venv/lib/python3.5/site-packages/asyncssh/public_key.py", line 26, in <module>
    from .cipher import get_encryption_params, get_cipher
  File ".../venv/lib/python3.5/site-packages/asyncssh/cipher.py", line 15, in <module>
    from .crypto import lookup_cipher
  File ".../venv/lib/python3.5/site-packages/asyncssh/crypto/__init__.py", line 21, in <module>
    from .pyca.ec import ECDSAPrivateKey, ECDSAPublicKey, ECDH
  File ".../venv/lib/python3.5/site-packages/asyncssh/crypto/pyca/ec.py", line 16, in <module>
    from cryptography.hazmat.backends.openssl import backend
  File ".../venv/lib/python3.5/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File ".../venv/lib/python3.5/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 17, in <module>
    from cryptography import utils, x509
  File ".../venv/lib/python3.5/site-packages/cryptography/x509/__init__.py", line 7, in <module>
    from cryptography.x509.base import (
  File ".../venv/lib/python3.5/site-packages/cryptography/x509/base.py", line 15, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File ".../venv/lib/python3.5/site-packages/cryptography/x509/extensions.py", line 19, in <module>
    from cryptography.hazmat.primitives import constant_time, serialization
  File ".../venv/lib/python3.5/site-packages/cryptography/hazmat/primitives/constant_time.py", line 9, in <module>
    from cryptography.hazmat.bindings._constant_time import lib
ImportError: dlopen(.../venv/lib/python3.5/site-packages/_cffi_backend.cpython-35m-darwin.so, 2): Symbol not found: _PyString_InternFromString
  Referenced from: .../venv/lib/python3.5/site-packages/_cffi_backend.cpython-35m-darwin.so
  Expected in: flat namespace
 in .../venv/lib/python3.5/site-packages/_cffi_backend.cpython-35m-darwin.so
```

This failure happens immediately; I am not able to get to the stage where I was able to trigger the segfault from last time.

Does this give you any clues?

**Comment by arigo** [comment]
Uh sorry, didn't actually run the tests on Python 3.  Fixing.

**Comment by arigo** [comment]
Fixed, sorry.  Try again?

**Comment by nchammas** [comment]
Now I'm getting the original segfault again, so it looks like that issue still remains.

Sorry I can't help with a more precise repro! I can instrument additional logging or something if it will help limit the source of the problem.

**Comment by arigo** [comment]
Sorry, at this point I can't guess what is wrong.  Can you provide me with a step-by-step guide on how to reproduce the bug, or is that not possible?

**Comment by arigo** [comment]
Actually, it would already help if you could provide me with a gdb backtrace in a debug version of Python 3.5 (in which you freshly installed cffi, which should be automatically compiled in debug mode as well).

**Comment by nchammas** [comment]
Reproducing the bug currently requires you have an EC2 account. Do you? It's pretty easy to reproduce if you can launch instances on EC2; I can walk you through the steps.

Otherwise, can you give me a pointer as to how to set Python up to give you that gdb backtrace? I did provide some info above by using `faulthandler.enable()`, but I'm guessing this info is different.

**Comment by arigo** [comment]
You need to build a debug-mode Python from sources---I guess there is no precompiled one around.

    hg clone -r 3.5 http://hg.python.org/cpython
    ./configure --with-pydebug --enable-shared --prefix=~/SOME/PATH
    make
    make install

Then you should be able to use ``virtualenv -p ~/some/path/bin/python venv-debug``.  Then:

    gdb --args ~/some/path/bin/python args...
    (gdb) run
    ...crash!...
    (gdb) backtrace

**Comment by arigo** [comment]
General note: according to the attached segfault.txt, the crash occurs inside the C function EVP_EncryptUpdate called via EVP_CipherUpdate from cffi.  It occurs quite late during shutdown, but it doesn't seem to involve any ``@def_extern``.  I don't really see how it relates to changing the callback method used by Cryptography.  Also, I don't really understand how it can segfault, unless the C function is called with bogus arguments (like an unexpected NULL or an already-deallocated pointer).  Is there in the C OpenSSL lib some way to explicitly shutdown the library, and does Cryptography call it?

**Comment by nchammas** [comment]
I'm having some trouble getting gdb to work well with debug Python; there seems to be some bad interaction with the Brew-installed Python I already have. I'll have to try again later.

**Comment by arigo** [comment]
Maybe: http://stackoverflow.com/questions/18978455/python-debugging-with-gdb-on-osx

**Comment by nchammas** [comment]
Closing issue for the following reasons:
* I haven't been able to look into this recently, and likely won't for some time.
* By the time I do get around to this, I imagine much will have changed.
* There is no easily sharable reproduction of the issue I'm reporting here.
