### ISSUE TITLE
X.509 OID 2.5.4.45 cannot be read because it's a bit string, not text

### ISSUE THREAD

**Issue by AndersMunch** [pyca/cryptography#3542]
\_\_repr\_\_ of the certificate object for the attached X.509 certificate fails with the exception
      ValueError: Unsupported ASN1 string type. Type: 3

I tracked it down to OID 2.5.4.45, which is of type "BIT STRING (64 bit)", according to https://lapo.it/asn1js/, which is the correct type for the OID if we are to believe http://www.alvestrand.no/objectid/2.5.4.45.html.

It looks like 'cryptography' is insisting name attributes must be text, and using decode_asn._asn1_string_to_utf8 accordingly, but in this case there is no text conversion and decode_asn1._asn1_string_to_bytes should have been used instead.

Attached, [sup_ds.zip](https://github.com/pyca/cryptography/files/1004488/sup_ds.zip) containing:
sup_ds.crt: A sample offending certificate.
sup_ds.py: Reproducing code.
sup_ds.out: Traceback when run against cryptography 1.8.1, openssl 1.1.0e.

**Comment by joernheissler** [comment]
The TBSCertificate ASN.1 definition contains fields "issuerUniqueID" and "subjectUniqueID". Are you sure that your uniqueIdentifier should actually go in the Subject?

**Comment by AndersMunch** [comment]
You're probably right that subjectUniqueID makes more sense, but I have no control over how these certificates are built, I have to read them as I find them. They're from the British smart-meter programme. 

I'm well aware that non-text name attributes are unusual. These certs trip up a lot of software, not just 'cryptography'. But it's not strictly illegal as far as I know.

I managed to read the certificate by monkeypatching `_decode_x509_name_entry` to fall back to `_asn1_string_to_bytes` if `_asn1_string_to_utf8` fails, and removing the `text_type` check in `NameAttribute.__init__`. I could make these changes into a proper pull request, if I could get some indication that it won't be rejected on principle.

**Comment by joernheissler** [comment]
rfc5280 4.1.2.4 states:

> The type of the component AttributeValue is determined by the AttributeType; in general it will be a DirectoryString.
> ...
> This specification does not restrict the set of attribute types that may appear in names.  However, conforming implementations MUST be prepared to receive certificates with issuer names containing the set of attribute types defined below.  This specification RECOMMENDS support for additional attribute types.

These "below" types are text types.

So I guess your certificate doesn't strictly violate the standard. But I still think someone messed up :-)

**Comment by joernheissler** [comment]
If all you want is to read the certs, you can also use https://github.com/wbond/asn1crypto/. But it lacks high-level functions like verifying if the cert is valid.

**Comment by reaperhulk** [comment]
I've implemented support for this, but now I'm wondering if I went too far by adding support for unused bits. @wbond I know you built an `OctetBitString` concept for things that are encoded as bit strings but in reality will always be octets and make no sense to address as bits. It looks like you use that for x500UniqueIdentifier. Did you find somewhere in the spec that requires that the unused bits always be zero?

**Comment by reaperhulk** [comment]
Is this still an issue people run into as 2022 approaches? Or has the British smart meter system gotten smarter? (The German smart meter program has also caused us grief in the past -- what is it about that industry...)

We could potentially support this now, but the public API declares `NameAttribute` values as always being `str` so we'd need to alter the API to allow `bytes` for this weird edge case, which isn't great.

**Comment by AndersMunch** [comment]
Oh yes, this is still an issue. I still maintain a monkeypatch that effects my 2017 PR, since without it there are certificates that I just can't read.  Problem unchanged, solution unchanged.

**Comment by wbond** [comment]
Someone I missed your comment a few years ago @reaperhulk. I don't recall exactly the development that went into that choice, but most likely it was reading certificates in the wild.

I did find https://openssl-users.openssl.narkive.com/RohW1xwV/invalid-x500uniqueidentifier-bitstring-in-openssl, where there is some discussion and Stephen Henson of OpenSSL implied unused bits will always be 0 for that use case. 🤷‍♂️
