### ISSUE TITLE
building cryptography 40.0.1 fails with OpenBSD latest version (7.3)

### ISSUE THREAD

**Issue by renaudallard** [pyca/cryptography#8722]
building cryptography fails with OpenBSD 7.3

> This crate is only compatible with OpenSSL (version 1.0.1 through 1.1.1, or 3.0.0), or LibreSSL 2.5           
        through 3.7.1, but a different version of OpenSSL was found. The build is now aborting                        
        due to this version mismatch.

OpenBSD 7.3 uses LibreSSL 3.7.2

If I modify openssl-sys-0.9.83/build/main.rs to add that new version, it still fails later with 
> thread 'main' panicked at 'unable to find openssl include path', build.rs:52:49

**Comment by reaperhulk** [comment]
Thanks for the report. This is fixed in the openssl-sys 0.9.85 crate, which we haven't had in a released version yet (https://github.com/pyca/cryptography/commit/684b710bea009efb062e5a5502583afe43390956). Given that OpenBSD 7.3 is now released I'm in favor of doing a 40.0.2 with this backport (along with a few other small changes).

**Comment by renaudallard** [comment]
great, I am wating for it :)
Thanks

**Comment by alex** [comment]
40.0.2 should resolve this.

**Comment by renaudallard** [comment]
Unfortunately, it's not solved, I have what I had before after patching for 3.7.2
>           Running `/tmp/pip-install-r_vov8mt/cryptography_bb4c8ed92a394ae1ae09fa8638bf2c96/src/rust/target/release/bu
ild/cryptography-rust-2d57360915c33af1/build-script-build`
      error: failed to run custom build command for `cryptography-rust v0.1.0 (/tmp/pip-install-r_vov8mt/cryptography_
bb4c8ed92a394ae1ae09fa8638bf2c96/src/rust)`
      
      Caused by:
        process didn't exit successfully: `/tmp/pip-install-r_vov8mt/cryptography_bb4c8ed92a394ae1ae09fa8638bf2c96/src
/rust/target/release/build/cryptography-rust-2d57360915c33af1/build-script-build` (exit status: 101)
        --- stdout
        cargo:rerun-if-changed=../_cffi_src/
        cargo:rustc-cfg=python_implementation="CPython"
      
        --- stderr
        thread 'main' panicked at 'unable to find openssl include path', build.rs:52:49

**Comment by alex** [comment]
This looks like you are not configuring your custom OpenSSL correctly, and therefore rust-openssl is unable to find your copy of LibreSSL.

See https://docs.rs/openssl/latest/openssl/#automatic / https://docs.rs/openssl/latest/openssl/#manual for configuration instructions. Our CI tests against 3.7.2, so we know it works.

**Comment by renaudallard** [comment]
I only did 'pip install cryptography' in a clean venv
I am now running with RUST_BACKTRACE=full

**Comment by renaudallard** [comment]
[cryptography.txt](https://github.com/pyca/cryptography/files/11233745/cryptography.txt)

**Comment by reaperhulk** [comment]
cryptography 39 built OpenSSL in a different way. 40.0.2 successfully compiles against 3.7.2 so there's a separate include path issue you're running into now. It is possible this is a bug in the [openssl-sys](https://github.com/sfackler/rust-openssl/) crate's autodiscovery, but you can try setting `OPENSSL_DIR` to the base path that contains the expected lib/include directories as a workaround.

**Comment by renaudallard** [comment]
If I `export OPENSSL_DIR=/usr`, build works fine. But that's still a regression over former versions.

**Comment by reaperhulk** [comment]
I believe the openssl-sys uses pkg-config to discover paths. Do you have that installed?

**Comment by renaudallard** [comment]
I had it installed in the system, but not in the venv. I installed it in the venv but that didn't change anything, still the same error. `        thread 'main' panicked at 'unable to find openssl include path', build.rs:52:49
`
